/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    "bg-emerald-100",
    "bg-emerald-200",
    "bg-emerald-300",
    "bg-emerald-400",
    "bg-emerald-500",
    "bg-emerald-600",
    "bg-emerald-700",
    "bg-emerald-800",
    "bg-emerald-900",
    "bg-yellow-100",
    "bg-yellow-200",
    "bg-yellow-300",
    "bg-yellow-400",
    "bg-yellow-500",
    "bg-yellow-600",
    "bg-yellow-700",
    "bg-yellow-800",
    "bg-yellow-900",
    "hover:bg-emerald-100",
    "hover:bg-emerald-200",
    "hover:bg-emerald-300",
    "hover:bg-emerald-400",
    "hover:bg-emerald-500",
    "hover:bg-emerald-600",
    "hover:bg-emerald-700",
    "hover:bg-emerald-800",
    "hover:bg-emerald-900",
    "hover:bg-yellow-100",
    "hover:bg-yellow-200",
    "hover:bg-yellow-300",
    "hover:bg-yellow-400",
    "hover:bg-yellow-500",
    "hover:bg-yellow-600",
    "hover:bg-yellow-700",
    "hover:bg-yellow-800",
    "hover:bg-yellow-900",
  ],
};
